FROM ubuntu:18.04
LABEL developer="siva"
ENV course="Docker"
ENV name="Siva"
CMD echo "Welcome to $course class , $name"
# Hello world 

# docker run --env course="K8s" --env name="prasad" ubuntu:env
